crds:
  enabled: true

defaultRules:
  create: true

alertmanager:
  enabled: true
  service:
    type: ClusterIP

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin123

  grafana.ini:
    server:
      root_url: https://nahui-ai.ddns.net/grafana
      serve_from_sub_path: true

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - nahui-ai.ddns.net
    path: /grafana
    pathType: Prefix
    tls:
      - secretName: nahui-ai-tls
        hosts:
          - nahui-ai.ddns.net

  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 10Gi

prometheus:
  enabled: true
  service:
    type: ClusterIP

  prometheusSpec:
    retention: 10d
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true
