apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: clinical-ai-platform
    app.kubernetes.io/version: {{ .Values.env.SERVICE_VERSION | quote }}
    app.kubernetes.io/managed-by: Helm
    observability.platform.io/enabled: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: clinical-ai-platform
        app.kubernetes.io/version: {{ .Values.env.SERVICE_VERSION | quote }}
        app.kubernetes.io/managed-by: Helm
        observability.platform.io/enabled: "true"
    spec:
      volumes:
        - name: proxy-routes
          configMap:
            name: gateway-proxy-routes
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: proxy-routes
              mountPath: /app/config
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
