apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: clinical-ai-platform
    observability.platform.io/enabled: "true"
spec:
  selector:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
