apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "document-reader.fullname" . }}
  labels:
    {{- include "document-reader.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "document-reader.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "document-reader.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: document-reader
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "document-reader.fullname" . }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            limits:
              {{- toYaml .Values.resources.limits | nindent 14 }}
              {{- if .Values.gpu.enabled }}
              nvidia.com/gpu: {{ .Values.gpu.count }}
              {{- end }}
            requests:
              {{- toYaml .Values.resources.requests | nindent 14 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
