apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "document-reader.fullname" . }}-redis
  labels:
    {{- include "document-reader.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
