replicaCount: 1

image:
  repository: vllm/vllm-openai
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

app:
  name: vllm-server
  namespace: cap-prod-vllm-server
  modelId: cyankiwi/Qwen3-VL-32B-Instruct-AWQ-4bit
  dtype: bfloat16
  maxModelLen: "6144"
  gpuMemoryUtilization: "0.92"
  port: 8000
  hfHome: /var/cache/huggingface
  extraArgs:
    - "--quantization"
    - "awq_marlin"

gpu:
  enabled: true
  count: 1

resources:
  requests:
    cpu: "2"
    memory: 20Gi
  limits:
    cpu: "6"
    memory: 40Gi

cache:
  mountPath: /var/cache/huggingface
  persistence:
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 30Gi

podLabels: {}
podAnnotations: {}

runtimeClassName: nvidia
nodeSelector:
  workload: large-models
tolerations: []
affinity: {}
