apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTH_TOKEN_SECRET: {{ .Values.auth.tokenSecret | quote }}
  REFRESH_TOKEN_SECRET: {{ .Values.auth.refreshTokenSecret | quote }}
  AUTH_USERS_JSON: {{ .Values.auth.usersJson | quote }}
