githubConfigUrl: "https://github.com/bmartinez-stgo/clinical-ai-platform"
githubConfigSecret: github-auth

runnerScaleSetName: "clinical-ai-local"

minRunners: 0
maxRunners: 2

template:
  spec:
    restartPolicy: Never

    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: DOCKER_HOST
            value: unix:///var/run/docker.sock
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
        securityContext:
          privileged: true
          runAsUser: 1001
          runAsGroup: 1001
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 4Gi
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: docker-sock
            mountPath: /var/run

      - name: dind
        image: docker:27-dind
        env:
          - name: DOCKER_TLS_CERTDIR
            value: ""
        command:
          - sh
          - -c
          - |
            dockerd \
              --host=unix:///var/run/docker.sock \
              --insecure-registry=registry:5000 \
              --insecure-registry=registry.cicd.svc.cluster.local:5000 &
            while [ ! -S /var/run/docker.sock ]; do
              sleep 1
            done
            chmod 666 /var/run/docker.sock
            wait
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: docker-sock
            mountPath: /var/run

    volumes:
      - name: work
        emptyDir: {}
      - name: docker-sock
        emptyDir: {}
