apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui-app
  namespace: cap-prod-open-webui
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://nahui-ai.ddns.net/workspace"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nahui-ai.ddns.net
      secretName: open-webui-tls
  rules:
    - host: nahui-ai.ddns.net
      http:
        paths:
          - path: /webui
            pathType: Prefix
            backend:
              service:
                name: open-webui
                port:
                  number: 8080
