replicaCount: 1

image:
  repository: registry:5000/clinical-rag
  tag: prod-latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8085
  targetPort: 8085

app:
  name: clinical-rag
  namespace: cap-prod-clinical-rag
  port: 8085
  logLevel: INFO
  serviceVersion: "0.1.0"
  environment: prod
  chromadbHost: chromadb
  chromadbPort: "8000"
  embeddingModel: paraphrase-multilingual-MiniLM-L12-v2

resources:
  requests:
    cpu: 250m
    memory: 768Mi
  limits:
    cpu: "1"
    memory: 1500Mi

chromadb:
  image: chromadb/chroma:0.5.23
  port: 8000
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    storageClassName: local-path
    size: 2Gi
    accessModes:
      - ReadWriteOnce

podLabels: {}
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
