apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb
  labels:
    {{- include "clinical-rag.labels" . | nindent 4 }}
    app.kubernetes.io/component: chromadb
spec:
  accessModes:
    {{- toYaml .Values.chromadb.persistence.accessModes | nindent 4 }}
  storageClassName: {{ .Values.chromadb.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.chromadb.persistence.size }}
