apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vllm-server.fullname" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "vllm-server.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.cache.persistence.accessModes | nindent 4 }}
  storageClassName: {{ .Values.cache.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.cache.persistence.size }}
