apiVersion: v1
kind: Service
metadata:
  name: {{ include "vllm-reasoning.fullname" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "vllm-reasoning.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "vllm-reasoning.selectorLabels" . | nindent 4 }}
