replicaCount: 1

image:
  repository: registry:5000/ai-diagnostic
  tag: prod-latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8083
  targetPort: 8083

app:
  name: ai-diagnostic
  namespace: cap-prod-ai-diagnostic
  port: 8083
  logLevel: INFO
  serviceVersion: "0.1.0"
  environment: prod
  aiEngineUrl: http://ai-engine.cap-prod-ai-engine.svc.cluster.local:8090/infer/clinical
  aiEngineTimeoutSeconds: "120"

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

podLabels: {}
podAnnotations: {}

nodeSelector: {}
tolerations: []
affinity: {}
