from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class LabDefinition:
    canonical_name: str
    loinc_code: str | None
    aliases: tuple[str, ...]
    default_unit_ucum: str | None = None
    canonical_name_es: str | None = None


LAB_DEFINITIONS: tuple[LabDefinition, ...] = (
    LabDefinition(
        canonical_name="Glucose",
        canonical_name_es="Glucosa",
        loinc_code="2345-7",
        aliases=("glucosa", "glucose"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Urea nitrogen",
        canonical_name_es="Nitrógeno ureico (BUN)",
        loinc_code="3094-0",
        aliases=("nitrogeno de urea en sangre", "bun", "blood urea nitrogen"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Urea",
        canonical_name_es="Urea",
        loinc_code="3094-0",
        aliases=("urea",),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Creatinine",
        canonical_name_es="Creatinina",
        loinc_code="2160-0",
        aliases=("creatinina", "creatinine"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Urea nitrogen/Creatinine",
        canonical_name_es="Razón BUN/Creatinina",
        loinc_code="3097-3",
        aliases=("relacion bun/creat", "razon bun/creatinina"),
        default_unit_ucum=None,
    ),
    LabDefinition(
        canonical_name="Urate",
        canonical_name_es="Ácido úrico",
        loinc_code="3084-1",
        aliases=("acido urico", "uric acid"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Phosphate",
        canonical_name_es="Fósforo",
        loinc_code="2777-1",
        aliases=("fosforo", "phosphorus"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Calcium",
        canonical_name_es="Calcio",
        loinc_code="17861-6",
        aliases=("calcio", "calcium"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Magnesium",
        canonical_name_es="Magnesio",
        loinc_code="19123-9",
        aliases=("magnesio", "magnesium"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Sodium",
        canonical_name_es="Sodio",
        loinc_code="2951-2",
        aliases=("sodio", "sodium"),
        default_unit_ucum="meq/L",
    ),
    LabDefinition(
        canonical_name="Potassium",
        canonical_name_es="Potasio",
        loinc_code="2823-3",
        aliases=("potasio", "potassium"),
        default_unit_ucum="meq/L",
    ),
    LabDefinition(
        canonical_name="Chloride",
        canonical_name_es="Cloro",
        loinc_code="2075-0",
        aliases=("cloro", "chloride"),
        default_unit_ucum="meq/L",
    ),
    LabDefinition(
        canonical_name="Estimated glomerular filtration rate",
        canonical_name_es="Tasa de filtración glomerular estimada",
        loinc_code="98979-8",
        aliases=(
            "tasa de filtracion glomerular estimada",
            "tfge",
            "egfr",
        ),
        default_unit_ucum="mL/min/{1.73_m2}",
    ),
    LabDefinition(
        canonical_name="Cholesterol",
        canonical_name_es="Colesterol total",
        loinc_code="2093-3",
        aliases=("colesterol", "cholesterol"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="HDL Cholesterol",
        canonical_name_es="Colesterol HDL",
        loinc_code="2085-9",
        aliases=("colesterol hdl", "hdl cholesterol"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="LDL Cholesterol",
        canonical_name_es="Colesterol LDL",
        loinc_code="18262-6",
        aliases=("colesterol ldl directo", "ldl cholesterol direct", "ldl directo"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Triglyceride",
        canonical_name_es="Triglicéridos",
        loinc_code="2571-8",
        aliases=("trigliceridos", "triglycerides"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Non-HDL Cholesterol",
        canonical_name_es="Colesterol no-HDL",
        loinc_code="43396-1",
        aliases=("colesterol no-hdl", "non-hdl cholesterol"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Atherogenic index",
        canonical_name_es="Índice aterogénico",
        loinc_code=None,
        aliases=("indice aterogenico",),
        default_unit_ucum=None,
    ),
    LabDefinition(
        canonical_name="LDL/HDL Ratio",
        canonical_name_es="Razón LDL/HDL",
        loinc_code="11054-4",
        aliases=("relacion ldl/hdl",),
        default_unit_ucum=None,
    ),
    LabDefinition(
        canonical_name="Small dense LDL",
        canonical_name_es="LDL pequeño y denso",
        loinc_code=None,
        aliases=("sd ldl",),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="VLDL Cholesterol",
        canonical_name_es="Colesterol VLDL",
        loinc_code="13458-5",
        aliases=("vldl colesterol",),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Total lipids",
        canonical_name_es="Lípidos totales",
        loinc_code=None,
        aliases=("lipidos totales",),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Serum phospholipids",
        canonical_name_es="Fosfolípidos en suero",
        loinc_code=None,
        aliases=("fosfolipidos en suero",),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="High sensitivity C reactive protein",
        canonical_name_es="Proteína C reactiva ultrasensible",
        loinc_code="30522-7",
        aliases=("proteina c reactiva ultrasensible",),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Total bilirubin",
        canonical_name_es="Bilirrubina total",
        loinc_code="1975-2",
        aliases=("bilirrubina total",),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Direct bilirubin",
        canonical_name_es="Bilirrubina directa",
        loinc_code="1968-7",
        aliases=("bilirrubina directa",),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Indirect bilirubin",
        canonical_name_es="Bilirrubina indirecta",
        loinc_code="1971-1",
        aliases=("bilirrubina indirecta",),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Aspartate aminotransferase",
        canonical_name_es="Aspartato aminotransferasa (AST)",
        loinc_code="1920-8",
        aliases=("ast (tgo)", "ast"),
        default_unit_ucum="U/L",
    ),
    LabDefinition(
        canonical_name="Alanine aminotransferase",
        canonical_name_es="Alanina aminotransferasa (ALT)",
        loinc_code="1742-6",
        aliases=("alt (tgp)", "alt"),
        default_unit_ucum="U/L",
    ),
    LabDefinition(
        canonical_name="AST/ALT Ratio",
        canonical_name_es="Razón AST/ALT",
        loinc_code=None,
        aliases=("relacion: ast/alt", "ast/alt"),
        default_unit_ucum=None,
    ),
    LabDefinition(
        canonical_name="Gamma glutamyl transferase",
        canonical_name_es="Gamma glutamil transferasa (GGT)",
        loinc_code="2324-2",
        aliases=("gama glutamil transpeptidasa",),
        default_unit_ucum="U/L",
    ),
    LabDefinition(
        canonical_name="Total protein",
        canonical_name_es="Proteínas totales",
        loinc_code="2885-2",
        aliases=("proteinas totales",),
        default_unit_ucum="g/dL",
    ),
    LabDefinition(
        canonical_name="Albumin",
        canonical_name_es="Albúmina",
        loinc_code="1751-7",
        aliases=("albumina",),
        default_unit_ucum="g/dL",
    ),
    LabDefinition(
        canonical_name="Globulin",
        canonical_name_es="Globulinas",
        loinc_code="10834-0",
        aliases=("globulinas",),
        default_unit_ucum="g/dL",
    ),
    LabDefinition(
        canonical_name="Albumin/Globulin Ratio",
        canonical_name_es="Razón Albúmina/Globulinas",
        loinc_code="1759-0",
        aliases=("relacion a/g",),
        default_unit_ucum=None,
    ),
    LabDefinition(
        canonical_name="Alkaline phosphatase",
        canonical_name_es="Fosfatasa alcalina",
        loinc_code="6768-6",
        aliases=("f. alcalina total", "fosfatasa alcalina total"),
        default_unit_ucum="U/L",
    ),
    LabDefinition(
        canonical_name="Lactate dehydrogenase",
        canonical_name_es="Lactato deshidrogenasa (LDH)",
        loinc_code="14804-9",
        aliases=("ldh",),
        default_unit_ucum="U/L",
    ),
    LabDefinition(
        canonical_name="Iron",
        canonical_name_es="Hierro sérico",
        loinc_code="2498-4",
        aliases=("hierro",),
        default_unit_ucum="ug/dL",
    ),
    LabDefinition(
        canonical_name="Unsaturated iron binding capacity",
        canonical_name_es="Capacidad de fijación de hierro no saturada (UIBC)",
        loinc_code="2501-6",
        aliases=("uibc",),
        default_unit_ucum="ug/dL",
    ),
    LabDefinition(
        canonical_name="Total iron binding capacity",
        canonical_name_es="Capacidad total de fijación de hierro (TIBC)",
        loinc_code="2500-8",
        aliases=("captacion de hierro",),
        default_unit_ucum="ug/dL",
    ),
    LabDefinition(
        canonical_name="Iron saturation",
        canonical_name_es="Saturación de hierro",
        loinc_code="2502-4",
        aliases=("porcentaje de saturacion de hierro",),
        default_unit_ucum="%",
    ),
    LabDefinition(
        canonical_name="Immunoglobulin G",
        canonical_name_es="Inmunoglobulina G",
        loinc_code="2465-3",
        aliases=("inmunoglobulina g", "immunoglobulina g"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Immunoglobulin A",
        canonical_name_es="Inmunoglobulina A",
        loinc_code="2458-8",
        aliases=("inmunoglobulina a", "immunoglobulina a"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Immunoglobulin M",
        canonical_name_es="Inmunoglobulina M",
        loinc_code="2472-9",
        aliases=("inmunoglobulina m", "immunoglobulina m"),
        default_unit_ucum="mg/dL",
    ),
    LabDefinition(
        canonical_name="Leukocytes",
        canonical_name_es="Leucocitos",
        loinc_code="6690-2",
        aliases=("leucocitos",),
    ),
    LabDefinition(
        canonical_name="Erythrocytes",
        canonical_name_es="Eritrocitos",
        loinc_code="789-8",
        aliases=("eritrocitos",),
    ),
    LabDefinition(
        canonical_name="Hemoglobin",
        canonical_name_es="Hemoglobina",
        loinc_code="718-7",
        aliases=("hemoglobina",),
        default_unit_ucum="g/dL",
    ),
    LabDefinition(
        canonical_name="Hematocrit",
        canonical_name_es="Hematocrito",
        loinc_code="4544-3",
        aliases=("hematocrito",),
        default_unit_ucum="%",
    ),
    LabDefinition(
        canonical_name="Mean corpuscular volume",
        canonical_name_es="Volumen corpuscular medio (VCM)",
        loinc_code="787-2",
        aliases=("volumen corpuscular medio", "volumen corp. medio", "vcm"),
        default_unit_ucum="fL",
    ),
    LabDefinition(
        canonical_name="Mean corpuscular hemoglobin",
        canonical_name_es="Hemoglobina corpuscular media (HCM)",
        loinc_code="785-6",
        aliases=("hemoglobina corpuscular media", "hemoglobina corp. media", "hcm"),
        default_unit_ucum="pg",
    ),
    LabDefinition(
        canonical_name="Mean corpuscular hemoglobin concentration",
        canonical_name_es="Concentración de hemoglobina corpuscular media (CHCM)",
        loinc_code="786-4",
        aliases=("conc. de hb corpuscular media", "conc. media de hemoglobina corp.", "chcm", "chorr"),
        default_unit_ucum="g/dL",
    ),
    LabDefinition(
        canonical_name="Erythrocyte distribution width CV",
        canonical_name_es="Ancho de distribución de eritrocitos CV",
        loinc_code="788-0",
        aliases=("ancho de distrib. de eritrocitos (cv)",),
        default_unit_ucum="%",
    ),
    LabDefinition(
        canonical_name="Erythrocyte distribution width SD",
        canonical_name_es="Ancho de distribución de eritrocitos SD",
        loinc_code="21000-5",
        aliases=("ancho de distrib. de eritrocitos (sd)",),
        default_unit_ucum="fL",
    ),
    LabDefinition(
        canonical_name="Platelets",
        canonical_name_es="Plaquetas",
        loinc_code="777-3",
        aliases=("plaquetas", "plequetas"),
    ),
    LabDefinition(
        canonical_name="Mean platelet volume",
        canonical_name_es="Volumen plaquetario medio",
        loinc_code="32623-1",
        aliases=("volumen plaquetario medio",),
        default_unit_ucum="fL",
    ),
    LabDefinition(
        canonical_name="Neutrophils Percent",
        canonical_name_es="Neutrófilos %",
        loinc_code="770-8",
        aliases=("neutrofilos", "segmentados"),
        default_unit_ucum="%",
    ),
    LabDefinition(
        canonical_name="Band neutrophils Percent",
        canonical_name_es="Bandas %",
        loinc_code="26507-4",
        aliases=("bandas",),
        default_unit_ucum="%",
    ),
    LabDefinition(
        canonical_name="Metamyelocytes Percent",
        canonical_name_es="Metamielocitos %",
        loinc_code="28541-1",
        aliases=("metamielocitos",),
        default_unit_ucum="%",
    ),
    LabDefinition(
        canonical_name="Myelocytes Percent",
        canonical_name_es="Mielocitos %",
        loinc_code="26498-6",
        aliases=("mielocitos",),
        default_unit_ucum="%",
    ),
    LabDefinition(
        canonical_name="Lymphocytes Percent",
        canonical_name_es="Linfocitos %",
        loinc_code="736-9",
        aliases=("linfocitos",),
        default_unit_ucum="%",
    ),
    LabDefinition(
        canonical_name="Monocytes Percent",
        canonical_name_es="Monocitos %",
        loinc_code="5905-5",
        aliases=("monocitos",),
        default_unit_ucum="%",
    ),
    LabDefinition(
        canonical_name="Eosinophils Percent",
        canonical_name_es="Eosinófilos %",
        loinc_code="713-8",
        aliases=("eosinofilos",),
        default_unit_ucum="%",
    ),
    LabDefinition(
        canonical_name="Basophils Percent",
        canonical_name_es="Basófilos %",
        loinc_code="706-2",
        aliases=("basofilos",),
        default_unit_ucum="%",
    ),
    LabDefinition(
        canonical_name="Urine color",
        canonical_name_es="Color de orina",
        loinc_code="5778-6",
        aliases=("color",),
    ),
    LabDefinition(
        canonical_name="Urine appearance",
        canonical_name_es="Aspecto de orina",
        loinc_code="5767-9",
        aliases=("aspecto",),
    ),
    LabDefinition(
        canonical_name="Urine specific gravity",
        canonical_name_es="Densidad de orina",
        loinc_code="5811-5",
        aliases=("densidad",),
    ),
    LabDefinition(
        canonical_name="Urine pH",
        canonical_name_es="pH de orina",
        loinc_code="5803-2",
        aliases=("ph",),
    ),
    LabDefinition(
        canonical_name="Urine leukocyte esterase",
        canonical_name_es="Esterasa leucocitaria en orina",
        loinc_code="5799-2",
        aliases=("esterasa leucocitaria",),
    ),
    LabDefinition(
        canonical_name="Urine nitrite",
        canonical_name_es="Nitritos en orina",
        loinc_code="5802-4",
        aliases=("nitritos",),
    ),
    LabDefinition(
        canonical_name="Urine protein",
        canonical_name_es="Proteínas en orina",
        loinc_code="20454-5",
        aliases=("proteinas",),
    ),
    LabDefinition(
        canonical_name="Urine glucose",
        canonical_name_es="Glucosa en orina",
        loinc_code="53328-1",
        aliases=("glucosa",),
    ),
    LabDefinition(
        canonical_name="Urine ketones",
        canonical_name_es="Cetonas en orina",
        loinc_code="57734-6",
        aliases=("cetonas",),
    ),
    LabDefinition(
        canonical_name="Urine bilirubin",
        canonical_name_es="Bilirrubina en orina",
        loinc_code="5770-3",
        aliases=("bilirrubina",),
    ),
    LabDefinition(
        canonical_name="Urine urobilinogen",
        canonical_name_es="Urobilinógeno en orina",
        loinc_code="5818-0",
        aliases=("urobilinogeno",),
    ),
    LabDefinition(
        canonical_name="Urine hemoglobin",
        canonical_name_es="Hemoglobina en orina",
        loinc_code="5794-3",
        aliases=("hemoglobina",),
    ),
)


UNIT_NORMALIZATION = {
    "mg/dl": "mg/dL",
    "mg / dl": "mg/dL",
    "mgdl": "mg/dL",
    "meq/l": "meq/L",
    "meq / l": "meq/L",
    "u/l": "U/L",
    "g/dl": "g/dL",
    "ug/dl": "ug/dL",
    "µg/dl": "ug/dL",
    "pg": "pg",
    "fl": "fL",
    "%": "%",
    "ml/min/1.73m2": "mL/min/{1.73_m2}",
    "ml/min/1.73 m2": "mL/min/{1.73_m2}",
    "ml/min/1.73m^2": "mL/min/{1.73_m2}",
    "ml/min/1.73 m^2": "mL/min/{1.73_m2}",
}
