name: Build API Local

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-image:
    runs-on: clinical-ai-local

    container:
      image: gcr.io/kaniko-project/executor:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push image
        run: |
          /kaniko/executor \
            --context $GITHUB_WORKSPACE \
            --dockerfile Dockerfile \
            --destination registry:5000/test-api:latest \
            --insecure \
            --skip-tls-verify
