replicaCount: 1

image:
  repository: registry:5000/ai-engine
  tag: prod-latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

app:
  name: ai-engine
  namespace: cap-prod-ai-engine
  port: 8090
  logLevel: DEBUG
  debugLogging: "true"
  serviceVersion: "0.1.0"
  environment: prod
  engineBackend: transformers
  engineId: Qwen/Qwen2.5-VL-7B-Instruct
  maxNewTokens: "2048"
  temperature: "0"
  devicePreference: cuda
  hfHome: /var/cache/huggingface
  transformersCache: /var/cache/huggingface/transformers
  generatedPreviewChars: "2000"
  pytorchCudaAllocConf: expandable_segments:True

gpu:
  enabled: true
  count: 1

resources:
  requests:
    cpu: "2"
    memory: 20Gi
  limits:
    cpu: "6"
    memory: 40Gi

cache:
  mountPath: /var/cache/huggingface
  persistence:
    enabled: true
    existingClaim: ""
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 30Gi

podLabels: {}
podAnnotations: {}

runtimeClassName: nvidia
nodeSelector:
  workload: large-models
tolerations: []
affinity: {}
